version: "3.1"

services: 
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ndstr
            MONGO_INITDB_ROOT_PASSWORD: ds012889
        ports:
            - 27017:27017
        networks:
            - backend


    nodestr-service:
        build: ./
        volumes: 
            - ./:/usr/src/nodestr
        ports: 
            - 3000:3000
        depends_on:
            - mongo
        networks:
            - backend


networks:
    backend:
        driver: bridge